void player_draw();
void player_init();
void player_update();
void delete_bullet(int i, char enemy_type[]);
float get_x_bullet(int j);
float get_y_bullet(int j);
float get_player_x();
float get_player_y();
int get_player_bullet_count();
int get_points();
int get_hit_points();
double get_power();
